defmodule XlWebsiteWeb.PageController do
  use XlWebsiteWeb, :controller
  alias XlWebsite.Parser
  alias XlWebsite.FileSystem
  alias XlWebsite.Exercises

  @home "Home"
  @exercises "Exercises"
  @about "About"
  @repo_prefix "xle-"
  @title_prefix "Elixirland - "

  def home(conn, _params) do
    conn
    |> assign(:page_title, @title_prefix <> "Elixir exercises with idiomatic example solutions")
    |> assign(:route, @home)
    |> render(:home)
  end

  def ecosystem(conn, _params) do
    ecosystem_data =
      FileSystem.read!(path_to("ecosystem.json"))
      |> Jason.decode!()
      |> Enum.sort_by(&Map.get(&1, "name"))

    conn
    |> assign(:page_title, @title_prefix <> "The Elixir ecosystem")
    |> assign(:route, "Ecosystem")
    |> assign(:ecosystem_data, ecosystem_data)
    |> render(:ecosystem)
  end

  defp path_to(file) do
    Path.join(:code.priv_dir(:xl_website), "/#{file}")
  end

  def exercises(conn, _params) do
    exercise_info = Exercises.get_exercises_info_only()

    conn
    |> assign(:page_title, @title_prefix <> @exercises)
    |> assign(:route, @exercises)
    |> assign(:exercises, exercise_info)
    |> render(:exercises)
  end

  def exercise(conn, %{"slug" => slug}) do
    case Exercises.get_exercise_by_full_name("elixirland/#{@repo_prefix}#{slug}") do
      nil ->
        conn
        |> put_status(:not_found)
        |> put_view(XlWebsiteWeb.ErrorHTML)
        |> render("404.html")

      exercise ->
        name = Parser.slug_to_name(slug)

        readme =
          Parser.filter_readme_sections(
            exercise.readme,
            ["Introduction", "Task", "How to get started", "Example solution"]
          )

        conn
        |> assign(:page_title, @title_prefix <> name)
        |> assign(:name, name)
        |> assign(:slug, slug)
        |> assign(:html_url, exercise.html_url)
        |> assign(:repo_prefix, @repo_prefix)
        |> assign(:readme, readme)
        |> assign(:topics, exercise.topics)
        |> render(:exercise)
    end
  end

  def about(conn, _params) do
    conn
    |> assign(:page_title, @title_prefix <> @about)
    |> assign(:route, @about)
    |> render(:about)
  end

  def reviewing(conn, _params) do
    conn
    |> assign(:page_title, @title_prefix <> "How does exercise reviewing work?")
    |> render(:reviewing)
  end

  # TODO: Replace hard-coded repo info with actual repo info

  def get_repos() do
    """
    [
      {
        "id": 828144262,
        "node_id": "R_kgDOMVx6hg",
        "name": "elixirland",
        "full_name": "elixirland/elixirland",
        "private": false,
        "owner": {
          "login": "elixirland",
          "id": 175476483,
          "node_id": "U_kgDOCnWPAw",
          "avatar_url": "https://avatars.githubusercontent.com/u/175476483?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/elixirland",
          "html_url": "https://github.com/elixirland",
          "followers_url": "https://api.github.com/users/elixirland/followers",
          "following_url": "https://api.github.com/users/elixirland/following{/other_user}",
          "gists_url": "https://api.github.com/users/elixirland/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/elixirland/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/elixirland/subscriptions",
          "organizations_url": "https://api.github.com/users/elixirland/orgs",
          "repos_url": "https://api.github.com/users/elixirland/repos",
          "events_url": "https://api.github.com/users/elixirland/events{/privacy}",
          "received_events_url": "https://api.github.com/users/elixirland/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/elixirland/elixirland",
        "description": "Introduction to Elixirland",
        "fork": false,
        "url": "https://api.github.com/repos/elixirland/elixirland",
        "forks_url": "https://api.github.com/repos/elixirland/elixirland/forks",
        "keys_url": "https://api.github.com/repos/elixirland/elixirland/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/elixirland/elixirland/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/elixirland/elixirland/teams",
        "hooks_url": "https://api.github.com/repos/elixirland/elixirland/hooks",
        "issue_events_url": "https://api.github.com/repos/elixirland/elixirland/issues/events{/number}",
        "events_url": "https://api.github.com/repos/elixirland/elixirland/events",
        "assignees_url": "https://api.github.com/repos/elixirland/elixirland/assignees{/user}",
        "branches_url": "https://api.github.com/repos/elixirland/elixirland/branches{/branch}",
        "tags_url": "https://api.github.com/repos/elixirland/elixirland/tags",
        "blobs_url": "https://api.github.com/repos/elixirland/elixirland/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/elixirland/elixirland/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/elixirland/elixirland/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/elixirland/elixirland/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/elixirland/elixirland/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/elixirland/elixirland/languages",
        "stargazers_url": "https://api.github.com/repos/elixirland/elixirland/stargazers",
        "contributors_url": "https://api.github.com/repos/elixirland/elixirland/contributors",
        "subscribers_url": "https://api.github.com/repos/elixirland/elixirland/subscribers",
        "subscription_url": "https://api.github.com/repos/elixirland/elixirland/subscription",
        "commits_url": "https://api.github.com/repos/elixirland/elixirland/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/elixirland/elixirland/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/elixirland/elixirland/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/elixirland/elixirland/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/elixirland/elixirland/contents/{+path}",
        "compare_url": "https://api.github.com/repos/elixirland/elixirland/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/elixirland/elixirland/merges",
        "archive_url": "https://api.github.com/repos/elixirland/elixirland/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/elixirland/elixirland/downloads",
        "issues_url": "https://api.github.com/repos/elixirland/elixirland/issues{/number}",
        "pulls_url": "https://api.github.com/repos/elixirland/elixirland/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/elixirland/elixirland/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/elixirland/elixirland/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/elixirland/elixirland/labels{/name}",
        "releases_url": "https://api.github.com/repos/elixirland/elixirland/releases{/id}",
        "deployments_url": "https://api.github.com/repos/elixirland/elixirland/deployments",
        "created_at": "2024-07-13T08:49:12Z",
        "updated_at": "2024-07-18T18:51:10Z",
        "pushed_at": "2024-07-18T18:51:08Z",
        "git_url": "git://github.com/elixirland/elixirland.git",
        "ssh_url": "git@github.com:elixirland/elixirland.git",
        "clone_url": "https://github.com/elixirland/elixirland.git",
        "svn_url": "https://github.com/elixirland/elixirland",
        "homepage": "https://elixirland.dev",
        "size": 27,
        "stargazers_count": 2,
        "watchers_count": 2,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 2,
        "default_branch": "main"
      },
      {
        "id": 828204085,
        "node_id": "R_kgDOMV1kNQ",
        "name": "xl-faker",
        "full_name": "elixirland/xl-faker",
        "private": false,
        "owner": {
          "login": "elixirland",
          "id": 175476483,
          "node_id": "U_kgDOCnWPAw",
          "avatar_url": "https://avatars.githubusercontent.com/u/175476483?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/elixirland",
          "html_url": "https://github.com/elixirland",
          "followers_url": "https://api.github.com/users/elixirland/followers",
          "following_url": "https://api.github.com/users/elixirland/following{/other_user}",
          "gists_url": "https://api.github.com/users/elixirland/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/elixirland/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/elixirland/subscriptions",
          "organizations_url": "https://api.github.com/users/elixirland/orgs",
          "repos_url": "https://api.github.com/users/elixirland/repos",
          "events_url": "https://api.github.com/users/elixirland/events{/privacy}",
          "received_events_url": "https://api.github.com/users/elixirland/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/elixirland/xl-faker",
        "description": "A package for generating fake data, convenient for use in Elixirland exercises.",
        "fork": false,
        "url": "https://api.github.com/repos/elixirland/xl-faker",
        "forks_url": "https://api.github.com/repos/elixirland/xl-faker/forks",
        "keys_url": "https://api.github.com/repos/elixirland/xl-faker/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/elixirland/xl-faker/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/elixirland/xl-faker/teams",
        "hooks_url": "https://api.github.com/repos/elixirland/xl-faker/hooks",
        "issue_events_url": "https://api.github.com/repos/elixirland/xl-faker/issues/events{/number}",
        "events_url": "https://api.github.com/repos/elixirland/xl-faker/events",
        "assignees_url": "https://api.github.com/repos/elixirland/xl-faker/assignees{/user}",
        "branches_url": "https://api.github.com/repos/elixirland/xl-faker/branches{/branch}",
        "tags_url": "https://api.github.com/repos/elixirland/xl-faker/tags",
        "blobs_url": "https://api.github.com/repos/elixirland/xl-faker/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/elixirland/xl-faker/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/elixirland/xl-faker/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/elixirland/xl-faker/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/elixirland/xl-faker/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/elixirland/xl-faker/languages",
        "stargazers_url": "https://api.github.com/repos/elixirland/xl-faker/stargazers",
        "contributors_url": "https://api.github.com/repos/elixirland/xl-faker/contributors",
        "subscribers_url": "https://api.github.com/repos/elixirland/xl-faker/subscribers",
        "subscription_url": "https://api.github.com/repos/elixirland/xl-faker/subscription",
        "commits_url": "https://api.github.com/repos/elixirland/xl-faker/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/elixirland/xl-faker/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/elixirland/xl-faker/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/elixirland/xl-faker/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/elixirland/xl-faker/contents/{+path}",
        "compare_url": "https://api.github.com/repos/elixirland/xl-faker/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/elixirland/xl-faker/merges",
        "archive_url": "https://api.github.com/repos/elixirland/xl-faker/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/elixirland/xl-faker/downloads",
        "issues_url": "https://api.github.com/repos/elixirland/xl-faker/issues{/number}",
        "pulls_url": "https://api.github.com/repos/elixirland/xl-faker/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/elixirland/xl-faker/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/elixirland/xl-faker/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/elixirland/xl-faker/labels{/name}",
        "releases_url": "https://api.github.com/repos/elixirland/xl-faker/releases{/id}",
        "deployments_url": "https://api.github.com/repos/elixirland/xl-faker/deployments",
        "created_at": "2024-07-13T12:30:13Z",
        "updated_at": "2024-07-19T10:48:16Z",
        "pushed_at": "2024-07-15T20:14:06Z",
        "git_url": "git://github.com/elixirland/xl-faker.git",
        "ssh_url": "git@github.com:elixirland/xl-faker.git",
        "clone_url": "https://github.com/elixirland/xl-faker.git",
        "svn_url": "https://github.com/elixirland/xl-faker",
        "homepage": "https://hex.pm/packages/xl_faker",
        "size": 93,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Elixir",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main"
      },
      {
        "id": 830698065,
        "node_id": "R_kgDOMYNyUQ",
        "name": "xl-template",
        "full_name": "elixirland/xl-template",
        "private": false,
        "owner": {
          "login": "elixirland",
          "id": 175476483,
          "node_id": "U_kgDOCnWPAw",
          "avatar_url": "https://avatars.githubusercontent.com/u/175476483?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/elixirland",
          "html_url": "https://github.com/elixirland",
          "followers_url": "https://api.github.com/users/elixirland/followers",
          "following_url": "https://api.github.com/users/elixirland/following{/other_user}",
          "gists_url": "https://api.github.com/users/elixirland/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/elixirland/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/elixirland/subscriptions",
          "organizations_url": "https://api.github.com/users/elixirland/orgs",
          "repos_url": "https://api.github.com/users/elixirland/repos",
          "events_url": "https://api.github.com/users/elixirland/events{/privacy}",
          "received_events_url": "https://api.github.com/users/elixirland/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/elixirland/xl-template",
        "description": "Template for exercise repositories",
        "fork": false,
        "url": "https://api.github.com/repos/elixirland/xl-template",
        "forks_url": "https://api.github.com/repos/elixirland/xl-template/forks",
        "keys_url": "https://api.github.com/repos/elixirland/xl-template/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/elixirland/xl-template/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/elixirland/xl-template/teams",
        "hooks_url": "https://api.github.com/repos/elixirland/xl-template/hooks",
        "issue_events_url": "https://api.github.com/repos/elixirland/xl-template/issues/events{/number}",
        "events_url": "https://api.github.com/repos/elixirland/xl-template/events",
        "assignees_url": "https://api.github.com/repos/elixirland/xl-template/assignees{/user}",
        "branches_url": "https://api.github.com/repos/elixirland/xl-template/branches{/branch}",
        "tags_url": "https://api.github.com/repos/elixirland/xl-template/tags",
        "blobs_url": "https://api.github.com/repos/elixirland/xl-template/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/elixirland/xl-template/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/elixirland/xl-template/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/elixirland/xl-template/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/elixirland/xl-template/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/elixirland/xl-template/languages",
        "stargazers_url": "https://api.github.com/repos/elixirland/xl-template/stargazers",
        "contributors_url": "https://api.github.com/repos/elixirland/xl-template/contributors",
        "subscribers_url": "https://api.github.com/repos/elixirland/xl-template/subscribers",
        "subscription_url": "https://api.github.com/repos/elixirland/xl-template/subscription",
        "commits_url": "https://api.github.com/repos/elixirland/xl-template/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/elixirland/xl-template/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/elixirland/xl-template/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/elixirland/xl-template/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/elixirland/xl-template/contents/{+path}",
        "compare_url": "https://api.github.com/repos/elixirland/xl-template/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/elixirland/xl-template/merges",
        "archive_url": "https://api.github.com/repos/elixirland/xl-template/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/elixirland/xl-template/downloads",
        "issues_url": "https://api.github.com/repos/elixirland/xl-template/issues{/number}",
        "pulls_url": "https://api.github.com/repos/elixirland/xl-template/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/elixirland/xl-template/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/elixirland/xl-template/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/elixirland/xl-template/labels{/name}",
        "releases_url": "https://api.github.com/repos/elixirland/xl-template/releases{/id}",
        "deployments_url": "https://api.github.com/repos/elixirland/xl-template/deployments",
        "created_at": "2024-07-18T19:49:37Z",
        "updated_at": "2024-07-18T19:49:45Z",
        "pushed_at": "2024-07-18T19:49:37Z",
        "git_url": "git://github.com/elixirland/xl-template.git",
        "ssh_url": "git@github.com:elixirland/xl-template.git",
        "clone_url": "https://github.com/elixirland/xl-template.git",
        "svn_url": "https://github.com/elixirland/xl-template",
        "homepage": null,
        "size": 0,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": true,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main"
      },
      {
        "id": 828145138,
        "node_id": "R_kgDOMVx98g",
        "name": "xle-book-club",
        "full_name": "elixirland/xle-book-club",
        "private": false,
        "owner": {
          "login": "elixirland",
          "id": 175476483,
          "node_id": "U_kgDOCnWPAw",
          "avatar_url": "https://avatars.githubusercontent.com/u/175476483?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/elixirland",
          "html_url": "https://github.com/elixirland",
          "followers_url": "https://api.github.com/users/elixirland/followers",
          "following_url": "https://api.github.com/users/elixirland/following{/other_user}",
          "gists_url": "https://api.github.com/users/elixirland/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/elixirland/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/elixirland/subscriptions",
          "organizations_url": "https://api.github.com/users/elixirland/orgs",
          "repos_url": "https://api.github.com/users/elixirland/repos",
          "events_url": "https://api.github.com/users/elixirland/events{/privacy}",
          "received_events_url": "https://api.github.com/users/elixirland/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/elixirland/xle-book-club",
        "description": "Build an simple Phoenix API for a book club.",
        "fork": false,
        "url": "https://api.github.com/repos/elixirland/xle-book-club",
        "forks_url": "https://api.github.com/repos/elixirland/xle-book-club/forks",
        "keys_url": "https://api.github.com/repos/elixirland/xle-book-club/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/elixirland/xle-book-club/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/elixirland/xle-book-club/teams",
        "hooks_url": "https://api.github.com/repos/elixirland/xle-book-club/hooks",
        "issue_events_url": "https://api.github.com/repos/elixirland/xle-book-club/issues/events{/number}",
        "events_url": "https://api.github.com/repos/elixirland/xle-book-club/events",
        "assignees_url": "https://api.github.com/repos/elixirland/xle-book-club/assignees{/user}",
        "branches_url": "https://api.github.com/repos/elixirland/xle-book-club/branches{/branch}",
        "tags_url": "https://api.github.com/repos/elixirland/xle-book-club/tags",
        "blobs_url": "https://api.github.com/repos/elixirland/xle-book-club/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/elixirland/xle-book-club/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/elixirland/xle-book-club/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/elixirland/xle-book-club/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/elixirland/xle-book-club/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/elixirland/xle-book-club/languages",
        "stargazers_url": "https://api.github.com/repos/elixirland/xle-book-club/stargazers",
        "contributors_url": "https://api.github.com/repos/elixirland/xle-book-club/contributors",
        "subscribers_url": "https://api.github.com/repos/elixirland/xle-book-club/subscribers",
        "subscription_url": "https://api.github.com/repos/elixirland/xle-book-club/subscription",
        "commits_url": "https://api.github.com/repos/elixirland/xle-book-club/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/elixirland/xle-book-club/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/elixirland/xle-book-club/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/elixirland/xle-book-club/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/elixirland/xle-book-club/contents/{+path}",
        "compare_url": "https://api.github.com/repos/elixirland/xle-book-club/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/elixirland/xle-book-club/merges",
        "archive_url": "https://api.github.com/repos/elixirland/xle-book-club/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/elixirland/xle-book-club/downloads",
        "issues_url": "https://api.github.com/repos/elixirland/xle-book-club/issues{/number}",
        "pulls_url": "https://api.github.com/repos/elixirland/xle-book-club/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/elixirland/xle-book-club/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/elixirland/xle-book-club/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/elixirland/xle-book-club/labels{/name}",
        "releases_url": "https://api.github.com/repos/elixirland/xle-book-club/releases{/id}",
        "deployments_url": "https://api.github.com/repos/elixirland/xle-book-club/deployments",
        "created_at": "2024-07-13T08:52:23Z",
        "updated_at": "2024-07-19T11:25:04Z",
        "pushed_at": "2024-07-19T11:25:01Z",
        "git_url": "git://github.com/elixirland/xle-book-club.git",
        "ssh_url": "git@github.com:elixirland/xle-book-club.git",
        "clone_url": "https://github.com/elixirland/xle-book-club.git",
        "svn_url": "https://github.com/elixirland/xle-book-club",
        "homepage": "",
        "size": 403,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Elixir",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": true,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "api",
          "ecto",
          "elixir",
          "phoenix",
          "postgresql"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "main"
      },
      {
        "id": 830974554,
        "node_id": "R_kgDOMYeqWg",
        "name": "xle-simple-chat-room",
        "full_name": "elixirland/xle-simple-chat-room",
        "private": false,
        "owner": {
          "login": "elixirland",
          "id": 175476483,
          "node_id": "U_kgDOCnWPAw",
          "avatar_url": "https://avatars.githubusercontent.com/u/175476483?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/elixirland",
          "html_url": "https://github.com/elixirland",
          "followers_url": "https://api.github.com/users/elixirland/followers",
          "following_url": "https://api.github.com/users/elixirland/following{/other_user}",
          "gists_url": "https://api.github.com/users/elixirland/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/elixirland/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/elixirland/subscriptions",
          "organizations_url": "https://api.github.com/users/elixirland/orgs",
          "repos_url": "https://api.github.com/users/elixirland/repos",
          "events_url": "https://api.github.com/users/elixirland/events{/privacy}",
          "received_events_url": "https://api.github.com/users/elixirland/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/elixirland/xle-simple-chat-room",
        "description": "Build a simple chat room with LiveView.",
        "fork": false,
        "url": "https://api.github.com/repos/elixirland/xle-simple-chat-room",
        "forks_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/forks",
        "keys_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/teams",
        "hooks_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/hooks",
        "issue_events_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/issues/events{/number}",
        "events_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/events",
        "assignees_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/assignees{/user}",
        "branches_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/branches{/branch}",
        "tags_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/tags",
        "blobs_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/languages",
        "stargazers_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/stargazers",
        "contributors_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/contributors",
        "subscribers_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/subscribers",
        "subscription_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/subscription",
        "commits_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/contents/{+path}",
        "compare_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/merges",
        "archive_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/downloads",
        "issues_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/issues{/number}",
        "pulls_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/labels{/name}",
        "releases_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/releases{/id}",
        "deployments_url": "https://api.github.com/repos/elixirland/xle-simple-chat-room/deployments",
        "created_at": "2024-07-19T11:24:22Z",
        "updated_at": "2024-07-19T11:27:59Z",
        "pushed_at": "2024-07-19T11:26:50Z",
        "git_url": "git://github.com/elixirland/xle-simple-chat-room.git",
        "ssh_url": "git@github.com:elixirland/xle-simple-chat-room.git",
        "clone_url": "https://github.com/elixirland/xle-simple-chat-room.git",
        "svn_url": "https://github.com/elixirland/xle-simple-chat-room",
        "homepage": "",
        "size": 0,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "elixir",
          "liveview",
          "phoenix",
          "postgresql"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main"
      },
      {
        "id": 830696485,
        "node_id": "R_kgDOMYNsJQ",
        "name": "xle-username-generator",
        "full_name": "elixirland/xle-username-generator",
        "private": false,
        "owner": {
          "login": "elixirland",
          "id": 175476483,
          "node_id": "U_kgDOCnWPAw",
          "avatar_url": "https://avatars.githubusercontent.com/u/175476483?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/elixirland",
          "html_url": "https://github.com/elixirland",
          "followers_url": "https://api.github.com/users/elixirland/followers",
          "following_url": "https://api.github.com/users/elixirland/following{/other_user}",
          "gists_url": "https://api.github.com/users/elixirland/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/elixirland/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/elixirland/subscriptions",
          "organizations_url": "https://api.github.com/users/elixirland/orgs",
          "repos_url": "https://api.github.com/users/elixirland/repos",
          "events_url": "https://api.github.com/users/elixirland/events{/privacy}",
          "received_events_url": "https://api.github.com/users/elixirland/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/elixirland/xle-username-generator",
        "description": "Build a Hex package that generates random usernames.",
        "fork": false,
        "url": "https://api.github.com/repos/elixirland/xle-username-generator",
        "forks_url": "https://api.github.com/repos/elixirland/xle-username-generator/forks",
        "keys_url": "https://api.github.com/repos/elixirland/xle-username-generator/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/elixirland/xle-username-generator/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/elixirland/xle-username-generator/teams",
        "hooks_url": "https://api.github.com/repos/elixirland/xle-username-generator/hooks",
        "issue_events_url": "https://api.github.com/repos/elixirland/xle-username-generator/issues/events{/number}",
        "events_url": "https://api.github.com/repos/elixirland/xle-username-generator/events",
        "assignees_url": "https://api.github.com/repos/elixirland/xle-username-generator/assignees{/user}",
        "branches_url": "https://api.github.com/repos/elixirland/xle-username-generator/branches{/branch}",
        "tags_url": "https://api.github.com/repos/elixirland/xle-username-generator/tags",
        "blobs_url": "https://api.github.com/repos/elixirland/xle-username-generator/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/elixirland/xle-username-generator/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/elixirland/xle-username-generator/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/elixirland/xle-username-generator/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/elixirland/xle-username-generator/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/elixirland/xle-username-generator/languages",
        "stargazers_url": "https://api.github.com/repos/elixirland/xle-username-generator/stargazers",
        "contributors_url": "https://api.github.com/repos/elixirland/xle-username-generator/contributors",
        "subscribers_url": "https://api.github.com/repos/elixirland/xle-username-generator/subscribers",
        "subscription_url": "https://api.github.com/repos/elixirland/xle-username-generator/subscription",
        "commits_url": "https://api.github.com/repos/elixirland/xle-username-generator/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/elixirland/xle-username-generator/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/elixirland/xle-username-generator/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/elixirland/xle-username-generator/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/elixirland/xle-username-generator/contents/{+path}",
        "compare_url": "https://api.github.com/repos/elixirland/xle-username-generator/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/elixirland/xle-username-generator/merges",
        "archive_url": "https://api.github.com/repos/elixirland/xle-username-generator/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/elixirland/xle-username-generator/downloads",
        "issues_url": "https://api.github.com/repos/elixirland/xle-username-generator/issues{/number}",
        "pulls_url": "https://api.github.com/repos/elixirland/xle-username-generator/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/elixirland/xle-username-generator/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/elixirland/xle-username-generator/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/elixirland/xle-username-generator/labels{/name}",
        "releases_url": "https://api.github.com/repos/elixirland/xle-username-generator/releases{/id}",
        "deployments_url": "https://api.github.com/repos/elixirland/xle-username-generator/deployments",
        "created_at": "2024-07-18T19:44:24Z",
        "updated_at": "2024-07-19T11:16:46Z",
        "pushed_at": "2024-07-19T11:16:42Z",
        "git_url": "git://github.com/elixirland/xle-username-generator.git",
        "ssh_url": "git@github.com:elixirland/xle-username-generator.git",
        "clone_url": "https://github.com/elixirland/xle-username-generator.git",
        "svn_url": "https://github.com/elixirland/xle-username-generator",
        "homepage": "",
        "size": 571,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": true,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "elixir",
          "hex",
          "mix"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main"
      }
    ]
    """
    |> Jason.decode!()
  end
end
